image: dtools/dev:php7.2

stages:
  - backend
  - frontend
  - deploy

composer:
  tags: [docker]
  stage: backend
  only:
    - test
    - production
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir .Build
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=./ --filename=composer.phar
    - export COMPOSER_ALLOW_SUPERUSER=1
    - export COMPOSER_MIRROR_PATH_REPOS=1
    - export COMPOSER_NO_INTERACTION=1
    - ./composer.phar install --no-dev --prefer-dist --optimize-autoloader
    - ./composer.phar dumpautoload --optimize
    - >
      rsync -rlp ./ .Build/
      --exclude-from=public/typo3conf/ext/base/GitlabCI/build-rsync-excludes.txt
  artifacts:
    expire_in: 60 minutes
    paths:
      - .Build

npm:
  tags: [docker]
  stage: frontend
  only:
    - test
    - production
  dependencies:
    - composer
  script:
    - cp package.json .Build/
    - cp package-lock.json .Build/
    - cp Gulpfile.js .Build/
    - cp gulp-config.js .Build/
    - cd .Build && npm install && cd -
    - cd .Build && npx gulp build-production && cd -
  artifacts:
    expire_in: 60 minutes
    paths:
      - .Build/public/typo3conf/ext/website/Resources/Public/JavaScript/
      - .Build/public/typo3conf/ext/website/Resources/Public/Stylesheets/

.deploy_common: &deploy_common
  tags: [docker]
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - >
      rsync -rlp -e "ssh -o StrictHostKeyChecking=no -p $SSH_PORT" --delete
      --exclude-from=.Build/public/typo3conf/ext/base/GitlabCI/deploy-rsync-excludes.txt
      .Build/ $SSH_LOGIN:$SSH_REMOTE_PATH

    - TYPO3_CONSOLE='php '$SSH_REMOTE_PATH'vendor/bin/typo3cms'
    - >
      ssh -p $SSH_PORT $SSH_LOGIN
      $TYPO3_CONSOLE' database:export | gzip > '$SSH_REMOTE_PATH'/backups/databases/beforedeploy.gz &&
      '$TYPO3_CONSOLE' cache:flush --files-only &&
      '$TYPO3_CONSOLE' database:updateschema "safe" &&
      '$TYPO3_CONSOLE' install:generatepackagestates  &&
      '$TYPO3_CONSOLE' install:fixfolderstructure &&
      '$TYPO3_CONSOLE' extension:setupactive &&
      '$TYPO3_CONSOLE' database:updateschema "destructive" &&
      '$TYPO3_CONSOLE' cache:flush'

deploy_test:
  <<: *deploy_common
  variables:
    SSH_LOGIN: xxx@xxx
    SSH_PORT: 22
    SSH_REMOTE_PATH: /xxx/
  dependencies:
    - composer
    - npm
  only:
    - test
  when: manual

deploy_production:
  <<: *deploy_common
  variables:
    SSH_LOGIN: xxx@xxx
    SSH_PORT: 22
    SSH_REMOTE_PATH: /xxx/
  dependencies:
    - composer
    - npm
  only:
    - production
  when: manual
